name: build

on:
    push: 
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build step
              run: cargo bbuild --verbose
            - name: Run tests
              run: cargo test --verbose